### PR TITLE
Update command

### PR DESCRIPTION
**Pull request by tomaszstrojny**
Hi,

I have changed and added some classes and traits to make it more readable and usable. I thought that you may not like my changes so I decided not to change your code. If you like my approach we can rearrange existing `Init` and `Install` commands to look and work similar.

I introduced concept of Managers which are responsible for doing some actions related to what are they meant to manage. I mean `PluginManager` class gives us ability to easily manage plugins and `ThemeManager` to easily manage themes. They differ from Installers because their job is not only to install plugins and themes, but give an abstraction layer to do some actions.

In the next version of `oc-bootstrapper` we can make Installers to use Managers to do their job. In Managers I heavily used your code, so moving Installers to use Managers should be easy and good decision.

I have added an `Artisan` class that has `call` method (as simple as that).

I have added some traits as well:
1. `CliIO` - classes that implements it can use `$this->input`, `$this->output` and `write()` method (input and output properties has to be set before using)
1. `ConfigMaker` which defines `$this->config` property and gives us `makeConfig()` method which will parse the config file. This should be use in every class that is going to use the config.
1. `ManageDirectory` which defines a few methods for managing filesystem, like `mkdir()`, `rmdir()`, `isEmpty()`, `unlink()` and `pwd()`.

Give me a note if you want me to fix anything. The update command was tested only on Homestead.

I haven't created the optional `git commit && push` yet, but I probably will create it soon.

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Thank you very much for this pull request! This is a great addition.

I didn't get around to review it in detail yet, but one thing that stood out to me was that the theme folder is deleted during the update. Since the theme itself contains data this is a destructive action. Currently there is no official way to update a theme in October.

I can see the use-case for this theme update feature but I feel like it should sit behind a separate `--with-theme` flag or something. What do you think?

**Comment by tomaszstrojny** [comment]
Oh, you are right. I have missed the case, sorry about that. This may be solved by a flag, but this is not exactly what we want, is it? The theme can be changed by users in the backend, so we actually should do something like you do in your update script. The update command should rather commit the changes done by users and than pull.

But this solution is not that easy. If the theme is changed by the backend users on the server and at the same time it's changed by the developers in the repo, the conflict may occur. And stashing the changes doesn't solve it as well. Do you have any better idea of how we could solve it?

Maybe some bright branches solution? How do you handle conflicts in your update script?

**Comment by tobias-kuendig** [comment]
We usually edit all content locally and publish it via git. If a customer does make changes to the content we git push it every n minutes via a cronjob. This way we almost never have any conflicts at all.

I feel like there is currently no way around this cronjob solution if you don't stricly only publish content one way (locally->server). The database layer for static content that is in the works might solve this issue.

Your git commit and pull idea won't work in this case since most deployments are run on the target server, this means the latest commits are most likely already pulled once the deploy script starts.

We also don't share themes among multiple sites. That's why the theme directory is part of the "project" and won't be updated separately (see https://github.com/OFFLINE-GmbH/octobertricks.com as an example). This way as soon as the deployment starts all changes to the theme are pulled by our deployment script. This updates the theme and all contents. Then we run composer and october update to update the external components. 

I guess we just have to ignore separate theme updates for the time being - or allow them via a flag in case someone is sure that it's safe to remove and re-download the whole theme directory for each deployment.

**Comment by tomaszstrojny** [comment]
You are right, there is no other way to update the theme. And I have to admit that your way of keeping and sharing projects (like October Tricks) is better than mine. I kept all plugins and themes in separate repos, while there is always a theme and something like 'configurator' plugin for every project (sometimes there are more than one). So that keeping them in a 'project repo' is much better idea.

I was thinking about `october update` like command that could be run using crontab as well. This way the core and plugins would stay updated. But of course in order to be sure that everything went as intended, we can run the command manually on the server, instead of manually updating whole project.

But you are right that theme can't be in the same box as plugins. Theme is almost always included in one project and only this one.

So I guess it's time to introduce another bootstrapper option like `october push` which will check if there were any changes made by the backend users to the theme and push if there were any :) Then we could use a project repo config in `october.yaml` so that command could use it instead of external bash scripts. I like bash scripts but keeping almost the same script in every project can be changed to another bootstrapper command, which looks rather easy to implement.

In the future I would see something like `october init <project_name> [git_repo]` parameter with the repo to pull the project from (including `october.yaml` or creating blank if it not exists).

How do you like it?

And please let me know how you like the idea of `Manager`s and do you want me to move existing bootstrapper commands to this approach?

**Comment by tobias-kuendig** [comment]
Running the update command during deployments makes sure that problems will be noticed immediately (unless you deploy and walk away from your computer :grin:).

I'm not sure of the benefits of tracking the repository in the october.yaml file. You already have a git repository checked out on your server, so a simple git push should already know where to send the files to.

I suggest you

1. update the PR so the theme data is left untouched
1. introduce the `october push` command that does essentialy this: https://github.com/OFFLINE-GmbH/octobertricks.com/blob/master/git.cron.sh

**Comment by tomaszstrojny** [comment]
Unless you deploy on Friday and go home :D 

You're right.

Write me please your thoughts on the `Manager`s.

**Comment by tobias-kuendig** [comment]
Your manager solution is great, I really like it! :+1: 	

Since we now have multiple "actions" it definitely makes sense to rename and restructure the classes.

**Comment by tomaszstrojny** [comment]
Themes removed from the update command.

I will create a new PR for the push command as we were talking.

If you don't mind I will also add a note to the readme file with description of project we assume user has to have in order to bootstrapper work as expected. I saw you have added the section with example project, I will refer to it.

**Comment by tobias-kuendig** [comment]
Thank you @czerwonyd, I will test this PR and report back.

**Comment by tobias-kuendig** [comment]
I have refactored the PluginManager code back into the PluginInstaller since it introduced a lot of redundant code.

Also, since the plugin updates are a destructive operation I've made them opt-in by marking them using a `^` in the configuration file. All plugins that provide this update flag will be removed during the update and re-downloaded.

Would you mind testing the latest `develop` state? If everything works as expected I will release a new version.

Thanks again @czerwonyd for the great addition!

**Comment by tomaszstrojny** [comment]
To be honest I was thinking about removing `Installers`, that's why there was so much redundand code.

What is more, I have removed them (installers) in my current development environment. I moved existing commands to use managers and changed `DeploymentInstaller`to become static factory, which in my opinion is much more accurate. I know I haven't pointed that out previously, but if you don't mind I will do it in another PR :)

**Pull request merged**
