### PR TITLE
Initial leave git repo in plugins

### PR DESCRIPTION
**Pull request by zlotnikd**
Sometimes we would like to install the application and keep the git repositories in our plugins.

This PR is adding an option to keep the .git repository in plugins when the cli pararmeter --with-git-directory is used.

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Thank you for this addition! I wonder if it would be better to have this configuration option in the `october.yaml` file as everything else. This way, you also don't have to remember to add the command line flag every time.

https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/templates/october.yaml#L21

**Comment by zlotnikd** [comment]
We thought about it but in such a situation we would have to modify october.yaml for every environment. I think it would be more convenient to solve it this way. What do you think about it? If you think that the solution you have proposed will be better then ok, we will do it.

**Comment by tobias-kuendig** [comment]
Sure, let's go with it, but move the config entry to the october.yaml file to keep everything in the same place :+1:

**Comment by zlotnikd** [comment]
Done, can you take a look at it now?

**Comment by tobias-kuendig** [comment]
This is looking great, thank you for the addition @yersey!

I'll release this as a new version shortly.

**Pull request merged**
